node {
    timeout(20){
    try 
{

        deleteDir() // Clean the workspace
        stage('Checkout Repo') {
            git branch: 'master',
                url: 'https://github.com/vitali-melnyk/Home.git'

        }
        stage('Start Docker Build for ... ') {
            sh "docker build -t vitalimelnyk/docker-home:${env.ENV} -f Docker-files/Dockerfile.nginx Docker-files"
        }

        if (env.PUSH_DOCKER.toBoolean()) {
        stage('Push on DockerHub') {
            sh "docker login -u vitalimelnyk -p ${env.PASS}"
            sh "docker push vitalimelnyk/docker-home:${env.ENV}"
        }
      }
      else {
        stage('Nothing to Push') {
            sh 'echo "Nothing to push.."'
        }
      }
      } catch (e) {
        sh 'exit 1'
        currentBuild.result = "FAILED"
        throw e
        } finally {
      }
}
}
